In [9]:
import pandas as pd
#pokemon = pd.read_csv (r'C:\Users\tusha\dataV2-labs\module-1\Dataframe-Calculations\Pokemon.csv')

rawdata1 = pd.read_csv (r'C:\Users\tusha\Project2--Amsterdam-Data-Anlytics\translated files\separation percentages.csv')
rawdata1 = pd.DataFrame(rawdata1)

In [11]:
rawdata1.head(59)

,"Bron: Rijkswaterstaat, CBS.",Unnamed: 1,Unnamed: 2,Unnamed: 3
0,Via: https://afvalmonitor.databank.nl/Jive,NaN,NaN,NaN
1,Over: scheidingspercentages en aangeboden huis...,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN
6,Gebieden,Perioden,Scheidingspercentage totaal huishoudelijk afva...,Totaal aangeboden huishoudelijk afval [Kilo's ...
7,Aalsmeer,2012,60.00%,536
8,Aalsmeer,2013,60.00%,512
9,Aalsmeer,2014,59.00%,488
10,Aalsmeer,2015,59.00%,495
11,Almere,2012,50.00%,501
12,Almere,2013,52.00%,472
13,Almere,2014,56.00%,480
14,Almere,2015,56.00%,464
15,Amstelveen,2012,46.00%,457
16,Amstelveen,2013,47.00%,445
17,Amstelveen,2014,48.00%,448
18,Amstelveen,2015,48.00%,434
19,Amsterdam,2012,13.00%,433
20,Amsterdam,2013,16.00%,423
21,Amsterdam,2014,17.00%,427
22,Amsterdam,2015,19.00%,399
23,Beemster,2012,54.00%,545
24,Beemster,2013,47.00%,469
25,Beemster,2014,51.00%,472
26,Beemster,2015,47.00%,443
27,Beverwijk,2012,32.00%,511
28,Beverwijk,2013,32.00%,495
29,Beverwijk,2014,33.00%,488
30,Beverwijk,2015,39.00%,531
31,Blaricum,2012,55.00%,533
32,Blaricum,2013,55.00%,512
33,Blaricum,2014,55.00%,518
34,Blaricum,2015,54.00%,506
35,Bloemendaal,2012,52.00%,557
36,Bloemendaal,2013,53.00%,543
37,Bloemendaal,2014,58.00%,553
38,Bloemendaal,2015,57.00%,549
39,Castricum,2012,59.00%,548
40,Castricum,2013,57.00%,529
41,Castricum,2014,58.00%,535
42,Castricum,2015,61.00%,540
43,Diemen,2012,29.00%,443
44,Diemen,2013,32.00%,417
45,Diemen,2014,33.00%,420
46,Diemen,2015,?,?
47,Edam-Volendam,2012,57.00%,637
48,Edam-Volendam,2013,57.00%,643
49,Edam-Volendam,2014,56.00%,637
50,Edam-Volendam,2015,55.00%,640
51,Gooise Meren,2012,55.00%,533
52,Gooise Meren,2013,55.00%,512
53,Gooise Meren,2014,55.00%,518
54,Gooise Meren,2015,54.00%,506
55,Haarlem,2012,33.00%,469
56,Haarlem,2013,31.00%,447
57,Haarlem,2014,30.00%,441
58,Haarlem,2015,32.00%,437